### ISSUE TITLE
installing plugins via signalk seems broken

### ISSUE THREAD

**Issue by mgrouch** [bareboat-necessities/lysmarine_gen#253]
installing plugins via signalk seems broken

**Comment by mgrouch** [comment]
```



4797 timing idealTree Completed in 171915ms
4798 timing command:install Completed in 172119ms
4799 verbose stack TypeError: Cannot read properties of null (reading 'matches')
4799 verbose stack     at Link.matches (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1114:41)
4799 verbose stack     at Link.canDedupe (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1068:15)
4799 verbose stack     at PlaceDep.pruneDedupable (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:468:14)
4799 verbose stack     at PlaceDep.placeInTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:329:14)
4799 verbose stack     at PlaceDep.place (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:216:10)
4799 verbose stack     at new PlaceDep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
4799 verbose stack     at PlaceDep.placeInTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:365:26)
4799 verbose stack     at PlaceDep.place (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:216:10)
4799 verbose stack     at new PlaceDep (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
4799 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:31
4800 verbose cwd /home/signalk/.signalk
4801 verbose Linux 5.15.61-v8+
4802 verbose node v16.17.1
4803 verbose npm  v8.19.2
4804 error Cannot read properties of null (reading 'matches')
4805 verbose exit 1

```

**Comment by mgrouch** [comment]
See also: https://github.com/npm/cli/issues/4367

**Comment by mgrouch** [comment]
Something like this should have worked from command line. (but it doesn't due to other dependencies issues)

```

cd /home/signalk/.signalk
sudo su signalk -c "rm ../.signalk/pnpm-lock.yaml; pnpm config set auto-install-peers true"
sudo su signalk -c "pnpm install \
                signalk-n2k-switching-emulator \
                --unsafe-perm"

```

**Comment by mgrouch** [comment]
it worked if I run this:



```

cd /home/signalk/.signalk

sudo su signalk -c "rm ../.signalk/pnpm-lock.yaml; pnpm config set auto-install-peers true"

sudo su signalk -c "pnpm add --save-peer tslib@^1.10.0"

sudo su signalk -c "pnpm install \
                signalk-n2k-switching-emulator \
                --unsafe-perm"

```

**Comment by mgrouch** [comment]
Linked request: https://github.com/SignalK/signalk-server/issues/1484

**Comment by mgrouch** [comment]
another example:


```

cd /home/signalk/.signalk
sudo su signalk -c "rm ../.signalk/pnpm-lock.yaml; pnpm config set auto-install-peers true"

sudo su signalk -c "pnpm install signalk-from-batch-format --unsafe-perm --save-peer"

```

**Comment by mgrouch** [comment]
for signalk-hwt901b-imu:

```
cd /home/signalk/.signalk
sudo su signalk -c "rm ../.signalk/pnpm-lock.yaml; pnpm config set auto-install-peers true"

sudo su signalk -c "pnpm install signalk-hwt901b-imu --unsafe-perm --save-peer"


```

**Comment by mgrouch** [comment]
BBN Marine OS version 2022-10-14 and up fixes this issue.
